# Generated by Django 6.1.1 on 2026-09-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True)),
                ('audit_id', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=500)),
                ('target_annotations', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ppe_compliance', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partial', 'Partially compliant'), ('non_compliant', 'Non-compliant'), ('not_visible', 'Not visible'), ('uncertain', 'Uncertain')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('taxonomy_version', models.CharField(default='1.0', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.image')),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='taxonomy_examples/')),
                ('taxonomy_version', models.CharField(default='1.0', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='annotation.taxonomycategory')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='annotation.annotation')),
                ('taxonomy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.taxonomyitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('image', 'annotator'), name='unique_image_per_annotator'),
        ),
    ]
