# Generated by Django 6.1.1 on 2026-09-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('audit_id', 'image_id'), name='unique_audit_image'),
        ),
        migrations.AddField(
            model_name='imageassignment',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageassignment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='annotation.image'),
        ),
        migrations.AddConstraint(
            model_name='imageassignment',
            constraint=models.UniqueConstraint(fields=('image', 'annotator'), name='unique_image_annotator_assignment'),
        ),
    ]
