# Generated by Django 6.1.1 on 2026-09-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_imageassignment_alter_image_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='storage_backend',
            field=models.CharField(default='onedrive', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='storage_item_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
