# Generated by Django 6.1.1 on 2026-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_image_storage_backend_image_storage_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='storage_item_id',
        ),
        migrations.AddField(
            model_name='image',
            name='storage_bucket',
            field=models.CharField(default='bohrim-app', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='storage_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='storage_backend',
            field=models.CharField(default='s3', max_length=20),
        ),
    ]
