# Generated by Django 6.1.1 on 2026-09-30 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_remove_image_storage_item_id_image_storage_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyitem',
            name='example_source_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_examples', to='annotation.image'),
        ),
    ]
