# Generated by Django 6.1.1 on 2026-09-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_taxonomyitem_example_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyitem',
            name='example_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
